# F1 Score

In [1]:
from sklearn.metrics import precision_recall_fscore_support, classification_report
import pandas as pd

In [2]:
ori_df = pd.read_csv('/Users/cookie/Desktop/Test/chunck_labeled/20k_labeled.csv')
need = ['user_id', 'labels']
ori_df = ori_df[need]

ori_df = ori_df[ori_df['labels'].notna()]

ori_df

user_id                                            labels
0    559963043  Audiophile.Brand_loyalty.Night_owl.high_consumer
1    530614473             Brand_loyalty.Culinarian.Mid_Consumer
2    546843256                                 Geek.Mid_Consumer
3    527948778                                 Geek.Mid_Consumer
4    513031983              Geek.Maker.Night_owl.common_Consumer
..         ...                                               ...
995  518667569                 Decisive.Fashionista.Mid_Consumer
996  547724823                           Culinarian.Mid_Consumer
997  561374969     Culinarian.Geek.Media_Aficionado.Mid_Consumer
998  519059386                       Car_Enthusiast.Mid_Consumer
999  521036929             Brand_loyalty.Culinarian.Mid_Consumer

[1000 rows x 2 columns]

In [3]:
pred_df = pd.read_csv('/Users/cookie/Desktop/Test/chuck_pred/pred_labeled_20k.csv')
pred_df

user_id                                             labels
0      559963043   Audiophile.Brand_loyalty.Night_owl.high_consumer
1      530614473              Brand_loyalty.Culinarian.Mid_Consumer
2      546843256                                  Geek.Mid_Consumer
3      527948778      Audiophile.Geek.Media_Aficionado.Mid_Consumer
4      513031983  Geek.Maker.Media_Aficionado.Mid_Consumer.Night...
...          ...                                                ...
19895  563305187  Audiophile.Car_Enthusiast.Media_Aficionado.Mid...
19896  519765357        Audiophile.Brand_loyalty.Geek.high_consumer
19897  557877771           Fashionista.Mid_Consumer.common_Consumer
19898  518433769  Brand_loyalty.Car_Enthusiast.Early_bird.Geek.M...
19899  560290557  Audiophile.Brand_loyalty.Culinarian.Homebody.M...

[19900 rows x 2 columns]

In [4]:
labeled_user_ids = ori_df['user_id'].tolist()
predicted_labels_df = pred_df[pred_df['user_id'].isin(labeled_user_ids)]

In [5]:
merged_df = ori_df.merge(pred_df, on='user_id', how='left', suffixes=('_true', '_pred'))
merged_df['labels_pred'].fillna('', inplace=True)

merged_df

/var/folders/8v/2l510pj11sxcxr76w30lfxhw0000gn/T/ipykernel_4870/2006739633.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['labels_pred'].fillna('', inplace=True)


user_id                                       labels_true  \
0    559963043  Audiophile.Brand_loyalty.Night_owl.high_consumer   
1    530614473             Brand_loyalty.Culinarian.Mid_Consumer   
2    546843256                                 Geek.Mid_Consumer   
3    527948778                                 Geek.Mid_Consumer   
4    513031983              Geek.Maker.Night_owl.common_Consumer   
..         ...                                               ...   
995  518667569                 Decisive.Fashionista.Mid_Consumer   
996  547724823                           Culinarian.Mid_Consumer   
997  561374969     Culinarian.Geek.Media_Aficionado.Mid_Consumer   
998  519059386                       Car_Enthusiast.Mid_Consumer   
999  521036929             Brand_loyalty.Culinarian.Mid_Consumer   

                                           labels_pred  
0     Audiophile.Brand_loyalty.Night_owl.high_consumer  
1                Brand_loyalty.Culinarian.Mid_Consumer  
2                                    Geek.Mid_Consumer  
3        Audiophile.Geek.Media_Aficionado.Mid_Consumer  
4    Geek.Maker.Media_Aficionado.Mid_Consumer.Night...  
..                                                 ...  
995           Decisive.Geek.Mid_Consumer.high_consumer  
996                            Culinarian.Mid_Consumer  
997      Culinarian.Geek.Media_Aficionado.Mid_Consumer  
998        Car_Enthusiast.Mid_Consumer.common_Consumer  
999              Brand_loyalty.Culinarian.Mid_Consumer  

[1000 rows x 3 columns]

In [6]:
merged_df['labels_true'] = merged_df['labels_true'].apply(lambda x: set(x.split('.')))
merged_df['labels_pred'] = merged_df['labels_pred'].apply(lambda x: set(x.split('.')))

merged_df

user_id                                        labels_true  \
0    559963043  {high_consumer, Night_owl, Audiophile, Brand_l...   
1    530614473          {Mid_Consumer, Culinarian, Brand_loyalty}   
2    546843256                               {Mid_Consumer, Geek}   
3    527948778                               {Mid_Consumer, Geek}   
4    513031983          {Maker, common_Consumer, Night_owl, Geek}   
..         ...                                                ...   
995  518667569              {Fashionista, Mid_Consumer, Decisive}   
996  547724823                         {Mid_Consumer, Culinarian}   
997  561374969  {Mid_Consumer, Media_Aficionado, Culinarian, G...   
998  519059386                     {Car_Enthusiast, Mid_Consumer}   
999  521036929          {Mid_Consumer, Culinarian, Brand_loyalty}   

                                           labels_pred  
0    {high_consumer, Night_owl, Audiophile, Brand_l...  
1            {Mid_Consumer, Culinarian, Brand_loyalty}  
2                                 {Mid_Consumer, Geek}  
3    {Mid_Consumer, Media_Aficionado, Audiophile, G...  
4    {Mid_Consumer, Geek, Maker, common_Consumer, M...  
..                                                 ...  
995      {high_consumer, Mid_Consumer, Decisive, Geek}  
996                         {Mid_Consumer, Culinarian}  
997  {Mid_Consumer, Media_Aficionado, Culinarian, G...  
998    {Car_Enthusiast, Mid_Consumer, common_Consumer}  
999          {Mid_Consumer, Culinarian, Brand_loyalty}  

[1000 rows x 3 columns]

In [7]:
y_true = merged_df['labels_true'].tolist()
y_pred = merged_df['labels_pred'].tolist()

In [8]:
all_labels = set.union(*y_true, *y_pred)
all_labels = sorted(all_labels)  # 确保标签顺序一致

In [9]:
# Transfer to one hot encoder
def encode_labels(labels, all_labels):
    return [1 if label in labels else 0 for label in all_labels]

In [10]:
y_true_encoded = [encode_labels(labels, all_labels) for labels in y_true]
y_pred_encoded = [encode_labels(labels, all_labels) for labels in y_pred]

In [11]:
# Calculate Precision, Recall, F1 Score
precision, recall, f1, _ = precision_recall_fscore_support(y_true_encoded, y_pred_encoded, average='micro')
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")

Precision: 0.8259
Recall: 0.9188
F1 Score: 0.8698


# Modularity

In [12]:
import sys
import os
import numpy as np
import networkx as nx
from datasets import load_dataset

sys.path.append(os.path.abspath("/Users/cookie/Desktop/LLMRecSys/Personality_Analysis/Model_training"))


In [13]:
from SSGB import preprocessing, GraphClustering  # 替换为你要调用的函数名


In [18]:
fi = '/Users/cookie/Desktop/Test/chunck_labeled/20k_labeled.csv'

access_token = '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'
original_embedding = load_dataset(
    "CookieLyu/Category_Codes",
    revision="1000k_average_embedded",
    token=access_token
)

augmented_embedding = load_dataset(
    "CookieLyu/Category_Codes",
    revision="1000k_average_embedded_aug",
    token=access_token
)

label_types = ['Night_owl', 'Early_bird', 'Decisive', 'Brand_loyalty', 'Maker', 'Homebody', 'Culinarian', 'Geek',
               'Photophile', 'Media_Aficionado', 'Audiophile', 'Fashionista', 'Lifestyle', 'Car_Enthusiast',
               'Caregiver', 'Health_Enthusiast', 'Farm', 'Sport', 'high_consumer', 'Mid_Consumer', 'common_Consumer']
k_neighbors = 5
threshold = 0.1
step = 3

preprocessor = preprocessing(fi, label_types, original_embedding, augmented_embedding)
all_features, seed_indices, merged_labels, consistency_loss = preprocessor.run()
OneHotLabels = preprocessor.get_OneHotEncoder_label()

graph_clustering = GraphClustering(all_features, k_neighbors, threshold, merged_labels, seed_indices, consistency_loss, step, OneHotLabels)
candidates, adj_matrix = graph_clustering.run()

G = graph_clustering.construct_graph()
G = nx.from_numpy_array(G)

# Calculate Modularity
from networkx.algorithms.community.quality import modularity

communities = nx.algorithms.community.label_propagation_communities(G)
modularity_score = modularity(G, communities)
print(f"Modularity: {modularity_score}")


[*] Reading from 20k_labeled.csv...
[*] Data preview:
------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   user_id                     20000 non-null  int64  
 1   average_time_float          20000 non-null  float64
 2   purchase_ratio              20000 non-null  float64
 3   average_price               20000 non-null  float64
 4   brand_loyalty_ratio         20000 non-null  float64
 5   most_freq_category_1        20000 non-null  object 
 6   category_1_activity_weight  20000 non-null  float64
 7   most_freq_category_2        20000 non-null  object 
 8   category_2_activity_weight  20000 non-null  float64
 9   most_freq_category_3        20000 non-null  object 
 10  category_3_activity_weight  20000 non-null  float64
 11  labels            

100%|██████████| 1000/1000 [00:00<00:00, 10885.31it/s]

[*] Preprocessing completed in 0.64 seconds.
[*] The result of OneHotEncoder is:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

Modularity: 0.5833005406703021
